#index:
#    path: /
#    controller: App\Controller\DefaultController::index
auth_google:
    path: /auth/
    controller: App\Controller\AuthController::google

counts:
    path: /api/counts/
    controller: App\Controller\CountController::index

refire:
    path: /api/refire
    controller: App\Controller\ReFireController::index
refire_all:
    path: /api/refire_all
    controller: App\Controller\ReFireController::all
